[phases.setup]
nixPkgs = ["python311", "pip", "chromium", "nss", "nspr", "atk", "cups", "dbus", "expat", "libdrm", "libxkbcommon", "mesa", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "xorg.libxcb", "pango", "cairo", "alsa-lib"]

[phases.install]
cmds = [
  "pip3 install -r requirements.txt",
  "playwright install chromium"
]

[start]
cmd = "python3 server.py"